name: test
on:
  push:

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        pip3 install scons
        choco install -y upx
        curl -s -O https://nvgt.gg/windev.zip
        7z x windev.zip -owindev
        scons -s no_upx=0
        release\nvgt test/tests.nvgt
        cd doc
        pip3 install -r requirements.txt
        cd OSL
        python3 make_osl_document.py
        cd ..
        python3 docgen.py
        cd ../install
        iscc nvgt.iss
        cd ..
    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nvgt_${{env.nvgt_version}}
        path: install/nvgt_${{env.nvgt_version}}.exe
